---

# Dataset metadata
default_dataset: &default_dataset
    type: PythonDataset
    delim: "\t"
    buffer_size: 5000
    shuffle: True
    map_tables:
        token2id:
            path: data/word2id.table
        pos2id:
            path: data/pos2id.table

    slots: 
        tokens: &default_slot
            index: 0
            type: sequence
            delim: " "
            map_table: token2id
            max_length: 200
            pad: 0
        tags:
            index: 1
            map_table: tag2id
            << : *default_slot
            

pred_dataset: &pred_dataset
    type: PythonDataset
    delim: "\t"
    buffer_size: 2000
    shuffle: True
    map_tables:
        token2id:
            path: data/word2id.table
        pos2id:
            path: data/pos2id.table

    slots: 
        tokens:
            << : *default_slot
        tags: 
            << : *default_slot
        nwords:
            index: 1
            type: value
            value_type: int64
        grams:
            index: 2
            map_table: gram2id
            << : *default_slot

train_dataset: &train_dataset
    path: data/train.conllu
    << : *default_dataset

dev_dataset: &dev_dataset
    shuffle: False
    path: data/dev.conllu
    << : *default_dataset

test_dataset: &test_dataset
    shuffle: False
    path: data/test.conllu
    << : *default_dataset

predict_dataset: &predict_dataset
    shuffle: False
    path: data/test.conllu
    << : *pred_dataset

logging:
    file: results/logging.out
    level: 3

# Model config
model:
    model_name: ChunkingModel
    use_word_pretrain_emb: False
    # word_emb_finetune: False
    word2vec_dict: 'data/embedding/embedding.50' 
    vocab_size : 4687

    use_crf: True
    max_length: 200
    emb_size: 50
    gram_emb_size: 64
    hidden_size : 256
    batch_size: 200
    optimizer: Adam
    learning_rate: 0.0005
    use_clip_by_norm: True
    decay_step: 300
    decay_rate: 0.9
    n_classes: 6
    dropout_rate: 0.3
    metric: NERMetric

# Estimator
estimator:
    type: PythonSequenceLabellingEstimator
    train_dataset: *train_dataset
    eval_datasets:
        # - *train_dataset
        - *dev_dataset
        # - *test_dataset
    eval_op_path: results/summary/eval.output
    # infer_dataset: *predict_dataset
    # infer_op_path: results/summary/infer.output

    batch_size: 200
    max_epochs: 40

    use_crf: True
    chunking: True
    use_entity_f1: True
    word2id: data/wordseg/sighan05_pku/char2id1.dict
    label2id: data/wordseg/sighan05_pku/label2id.dict
    infer2id: data/wordseg/sighan05_pku/infer2id.dict
    checkpoint_dir: results/wordseg_pku/lstm_crf_short
    best_checkpoint_dir: results/best
    model_name: region_sequence_labbelling_model
    save_checkpoints_steps: 2000
    eval_interval_steps: 100
    max_training_steps: 4000
    log_every_n_steps: 100
    display_eval: False